### ISSUE TITLE
How to run on local machine

### ISSUE THREAD

**Issue by marshallmathers78910** [GantMan/tictactoe-ai-tfjs#4]
First of all I appreciate your effort to share your great project. I have been trying to run your code on my computer by downloading the code and simply opening the index.html file. However only a blank white background is visible. I tried to modify your code and manually link the css file using <link rel=""...> and the background started to show up. Did you do this intentionally or is there any other way in which I can run your code directly without making any changes to it?
My apologies in advance if my question seems stupid. I'm new to web development and ML.

**Comment by marshallmathers78910** [comment]
nvm i didnt read through the contents in depth
all you have to do is type "npm start"

**Comment by GantMan** [comment]
If you'd like to do a PR to the readme with a "How to run this project" section, I'd merge it!

**Comment by Aisultan14366** [comment]
pls tell how to run it

**Comment by GantMan** [comment]
I think you just pull it down, do a yarn install, and then a yarn run.   Maybe I'm missing something.  Did you try the normal React website running instructions?
